version: '3.8'

services:
  app:
    build: .
    container_name: pathfinder_app
    working_dir: /var/www
    volumes:
      - .:/var/www
    expose:
      - "9000"
    depends_on:
      - db
    networks:
      - laravel_network

  nginx:
    image: nginx:latest
    container_name: pathfinder_nginx
    ports:
      - "8000:80"
    volumes:
      - .:/var/www
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - laravel_network

  db:
    image: mysql:8.0
    container_name: pathfinder_db
    restart: always
    environment:
      MYSQL_DATABASE: pathfinder
      MYSQL_ROOT_PASSWORD: 12345
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - laravel_network

volumes:
  dbdata:

networks:
  laravel_network:
    driver: bridge
